"""Initial schema

Revision ID: 515c56cbe7a5
Revises: 
Create Date: 2026-09-01 22:45:10.105710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '515c56cbe7a5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_descriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('raw_html', sa.Text(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=False),
    sa.Column('parsed_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_descriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_descriptions_id'), ['id'], unique=False)

    op.create_table('resumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('parsed_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resumes_id'), ['id'], unique=False)

    op.create_table('gap_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('analysis_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job_descriptions.id'], ),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gap_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gap_analyses_id'), ['id'], unique=False)

    op.create_table('improved_resumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('improved_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job_descriptions.id'], ),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('improved_resumes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_improved_resumes_id'), ['id'], unique=False)

    op.create_table('project_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('plan_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['gap_analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_plans_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_plans_id'))

    op.drop_table('project_plans')
    with op.batch_alter_table('improved_resumes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_improved_resumes_id'))

    op.drop_table('improved_resumes')
    with op.batch_alter_table('gap_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gap_analyses_id'))

    op.drop_table('gap_analyses')
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resumes_id'))

    op.drop_table('resumes')
    with op.batch_alter_table('job_descriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_descriptions_id'))

    op.drop_table('job_descriptions')
    # ### end Alembic commands ###
